apps/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    # Default
    path("admin/", admin.site.urls),
    # Custom
    path("", RedirectView.as_view(pattern_name="account:login-view", permanent=False)),
    path("account/", include(("apps.account.urls", "apps.account"), namespace="account")),
    path("faction/", include(("apps.faction.urls", "apps.faction"), namespace="faction")),
    path("finance/", include(("apps.finance.urls", "apps.finance"), namespace="finance")),
    path("item/", include(("apps.item.urls", "apps.item"), namespace="item")),
    path("quest/", include(("apps.quest.urls", "apps.quest"), namespace="quest")),
    path("savegame/", include(("apps.savegame.urls", "apps.savegame"), namespace="savegame")),
    path(
        "skirmish/",
        include(("apps.skirmish.urls", "apps.skirmish"), namespace="skirmish"),
    ),
    path("training/", include(("apps.training.urls", "apps.training"), namespace="training")),
    path("warrior/", include(("apps.warrior.urls", "apps.month"), namespace="warrior")),
    path("month/", include(("apps.month.urls", "apps.month"), namespace="month")),
]

apps/item/urls.py
from django.urls import path

from apps.item import views

urlpatterns = [
    path("<int:pk>/sell", views.ItemSellView.as_view(), name="item-sell-view"),
    path("<int:pk>/buy", views.ItemBuyView.as_view(), name="item-buy-view"),
]

apps/item/models/item.py
import typing

from django.db import models

from apps.common.domain.dice import DiceNotation
from apps.item.managers.item import ItemManager
from apps.item.models.item_type import ItemType

if typing.TYPE_CHECKING:
    from apps.skirmish.models.warrior import Warrior


class Item(models.Model):
    class ConditionChoices(models.IntegerChoices):
        CONDITION_RUSTY = 1, "Rusty"
        CONDITION_CHEAP = 2, "Cheap"
        CONDITION_TRADITIONAL = 3, "Traditional"
        CONDITION_SUPERIOR = 4, "Superior"

    condition = models.PositiveSmallIntegerField(
        "Condition", choices=ConditionChoices.choices, default=ConditionChoices.CONDITION_TRADITIONAL
    )
    type = models.ForeignKey(ItemType, verbose_name="Type", on_delete=models.CASCADE)
    price = models.PositiveSmallIntegerField("Price")
    modifier = models.SmallIntegerField("Modifier", default=0, help_text='2d4+7 - this is the "7"')
    owner = models.ForeignKey(
        "faction.Faction", verbose_name="Owning faction", null=True, blank=True, on_delete=models.CASCADE
    )

    savegame = models.ForeignKey("savegame.Savegame", verbose_name="Savegame", on_delete=models.CASCADE)

    objects = ItemManager()

    class Meta:
        verbose_name = "Item"
        verbose_name_plural = "Items"
        default_related_name = "items"

    def __str__(self) -> str:
        return f"{self.display_name} ({self.type.base_value}{self.get_modifier_as_string()})"

    @property
    def display_name(self) -> str:
        if self.type.is_fallback:
            return f"{self.type.name}"
        return f"{self.get_condition_display()} {self.type.name}"

    @property
    def is_weapon(self) -> bool:
        return self.type.function == ItemType.FunctionChoices.FUNCTION_WEAPON

    @property
    def is_armor(self) -> bool:
        return self.type.function == ItemType.FunctionChoices.FUNCTION_ARMOR

    @property
    def worn_by(self) -> typing.Optional["Warrior"]:
        if self.type.function == ItemType.FunctionChoices.FUNCTION_WEAPON and self.warrior_weapon:
            return self.warrior_weapon
        if self.type.function == ItemType.FunctionChoices.FUNCTION_ARMOR and self.warrior_armor:
            return self.warrior_armor

        return None

    @property
    def expectancy_value(self) -> float:
        return DiceNotation(dice_string=self.type.base_value, modifier=self.modifier).expectancy_value

    def get_modifier_as_string(self) -> str:
        return f"+{self.modifier}" if self.modifier >= 0 else f"{self.modifier}"

apps/item/models/item_type.py
from django.db import models

from apps.common.validators import dice_notation


class ItemType(models.Model):
    class FunctionChoices(models.IntegerChoices):
        FUNCTION_WEAPON = 1, "Weapon"
        FUNCTION_ARMOR = 2, "Armor"

    name = models.CharField("Name", max_length=75)
    function = models.PositiveSmallIntegerField("Function", choices=FunctionChoices.choices)
    base_value = models.CharField("Value", validators=[dice_notation], max_length=10)
    svg_image_name = models.CharField("SVG image name", max_length=50)
    is_fallback = models.BooleanField("Is fallback", default=0)

    class Meta:
        verbose_name = "Item type"
        verbose_name_plural = "Item types"
        default_related_name = "item_types"

    def __str__(self) -> str:
        return f"{self.name} ({self.get_function_display()})"

apps/skirmish/models/item.py
from django.db import models

from apps.core.validators import dice_notation
from apps.faction.models.faction import Faction
from apps.skirmish.managers.item import ItemManager


class Item(models.Model):
    class TypeChoices(models.IntegerChoices):
        TYPE_WEAPON = 1, "Weapon"
        TYPE_ARMOR = 2, "Armor"

    type = models.PositiveSmallIntegerField("Type", choices=TypeChoices.choices)
    price = models.PositiveSmallIntegerField("Price")
    value = models.CharField("Value", validators=[dice_notation], max_length=10)
    owner = models.ForeignKey(Faction, verbose_name="Owning faction", on_delete=models.CASCADE)

    objects = ItemManager()

    class Meta:
        verbose_name = "Item"
        verbose_name_plural = "Items"
        default_related_name = "items"

    def __str__(self):
        return f"{self.get_type_display()} ({self.value}, {self.owner})"

    @property
    def is_weapon(self):
        return self.type == self.TypeChoices.TYPE_WEAPON

    @property
    def is_armor(self):
        return self.type == self.TypeChoices.TYPE_ARMOR

    @property
    def worn_by(self):
        if self.type == self.TypeChoices.TYPE_WEAPON and self.warrior_weapon:
            return self.warrior_weapon
        elif self.type == self.TypeChoices.TYPE_ARMOR and self.warrior_armor:
            return self.warrior_armor

apps/item/views.py
import json
from http import HTTPStatus

from django.http import HttpResponse
from django.views import generic
from django.views.generic.detail import SingleObjectMixin
from queuebie.runner import handle_message

from apps.finance.models import Transaction
from apps.item.messages.commands.item import BuyItem, SellItem
from apps.item.models.item import Item
from apps.savegame.models.savegame import Savegame


class ItemSellView(SingleObjectMixin, generic.View):
    model = Item
    http_method_names = ("post",)

    def post(self, *args, **kwargs):
        obj = self.get_object()
        current_savegame: Savegame = Savegame.objects.get_current_savegame(user_id=self.request.user.id)

        handle_message(SellItem(selling_faction=obj.owner, item=obj, month=current_savegame.current_month))

        response = HttpResponse(status=HTTPStatus.OK)
        response["HX-Trigger"] = json.dumps(
            {
                "loadFactionItemList": "-",
                "loadFactionWarriorList": "-",
            }
        )
        return response


class ItemBuyView(SingleObjectMixin, generic.View):
    model = Item
    http_method_names = ("post",)

    def post(self, *args, **kwargs):
        obj = self.get_object()
        current_savegame: Savegame = Savegame.objects.get_current_savegame(user_id=self.request.user.id)

        current_balance = Transaction.objects.current_balance(savegame_id=current_savegame.id)
        if current_balance < obj.price:
            response = HttpResponse(status=HTTPStatus.NO_CONTENT)
            response["HX-Trigger"] = json.dumps(
                {
                    "notification": "You don't have enough money to buy this item.",
                }
            )
            return response

        handle_message(
            BuyItem(
                price=obj.price,
                item=obj,
                buying_faction=current_savegame.player_faction,
                month=current_savegame.current_month,
            )
        )

        response = HttpResponse(status=HTTPStatus.OK)
        response["HX-Trigger"] = json.dumps(
            {
                "loadShopItemList": "-",
            }
        )
        return response

apps/item/templates/item/components/item_buy_card.html
    {% load l10n %}
<div class="uk-card uk-card-default uk-margin-bottom">
    <div class="uk-card-header">
        <div id="item-card-{{ item.id|unlocalize }}" class="uk-grid-small uk-flex-middle" uk-grid>
            <div class="uk-width-auto">
                {% include 'common/components/svg_icon.html' with icon_name=item.type.svg_image_name size='xl' %}
            </div>
            <div class="uk-width-expand">
                <h3 class="uk-card-title uk-margin-remove-bottom">
                    {{ item.display_name }}
                </h3>
                <p class="uk-text-meta uk-margin-remove-top">
                    <i class="fa-solid fa-sack-xmark"></i> <i>{{ item.price }} silver</i>&nbsp;
                    {% include 'common/components/svg_icon.html' with icon_name='axe-sword' %}
                    <i>{{ item.type.base_value }}{{ item.get_modifier_as_string }}</i>&nbsp;
                    <i class="fa-solid fa-dice"></i> <i>{{ item.expectancy_value }}</i>
                </p>
            </div>
        </div>
    </div>
    <div class="uk-card-footer">
        <a hx-post="{% url 'item:item-buy-view' item.id %}"
           hx-target="#item-card-{{ item.id|unlocalize }}"
           hx-swap="none"
           class="uk-button uk-button-text">Buy</a>
    </div>
</div>

apps/item/templates/item/components/item_card.html
    {% load l10n %}
<div class="uk-card uk-card-default uk-margin-bottom">
    <div class="uk-card-header">
        <div id="item-card-{{ item.id|unlocalize }}" class="uk-grid-small uk-flex-middle" uk-grid>
            <div class="uk-width-auto">
                {% include 'core/compontents/svg_icon.html' with icon_name=item.type.svg_image_name size='xl' %}
            </div>
            <div class="uk-width-expand">
                <h3 class="uk-card-title uk-margin-remove-bottom">
                    {{ item.display_name }}
                </h3>
                <p class="uk-text-meta uk-margin-remove-top">
                    <i class="fa-solid fa-sack-xmark"></i> <i>{{ item.price }} silver</i>&nbsp;
                    {% include 'core/compontents/svg_icon.html' with icon_name='axe-sword' %}
                    <i>{{ item.type.base_value }}{{ item.get_modifier_as_string }}</i>&nbsp;
                    <i class="fa-solid fa-dice"></i> <i>{{ item.expectancy_value }}</i>
                </p>
            </div>
        </div>
    </div>
    <div class="uk-card-body uk-text-left">
        <p>Worn by: {{ item.worn_by|default_if_none:"-" }}</p>
    </div>
    <div class="uk-card-footer">
        <a hx-post="{% url 'item:item-sell-view' item.id %}"
           hx-target="#item-card-{{ item.id|unlocalize }}"
           hx-swap="none"
            {# TODO: implement buy items #}
            {# TODO: card is reused for selling and buying -> fix this since they are not the same #}
           class="uk-button uk-button-text">Sell (buy not implemented)</a>
    </div>
</div>

apps/item/templates/item/components/item_sell_card.html
{% load l10n %}
<div class="uk-card uk-card-default uk-margin-bottom">
    <div class="uk-card-header">
        <div id="item-card-{{ item.id|unlocalize }}" class="uk-grid-small uk-flex-middle" uk-grid>
            <div class="uk-width-auto">
                {% include 'common/components/svg_icon.html' with icon_name=item.type.svg_image_name size='xl' %}
            </div>
            <div class="uk-width-expand">
                <h3 class="uk-card-title uk-margin-remove-bottom">
                    {{ item.display_name }}
                </h3>
                <p class="uk-text-meta uk-margin-remove-top">
                    <i class="fa-solid fa-sack-xmark"></i> <i>{{ item.price }} silver</i>&nbsp;
                    {% include 'common/components/svg_icon.html' with icon_name='axe-sword' %}
                    <i>{{ item.type.base_value }}{{ item.get_modifier_as_string }}</i>&nbsp;
                    <i class="fa-solid fa-dice"></i> <i>{{ item.expectancy_value }}</i>
                </p>
            </div>
        </div>
    </div>
    <div class="uk-card-body uk-text-left">
        <p>Worn by: {{ item.worn_by|default_if_none:"-" }}</p>
    </div>
    <div class="uk-card-footer">
        <a hx-post="{% url 'item:item-sell-view' item.id %}"
           hx-target="#item-card-{{ item.id|unlocalize }}"
           hx-swap="none"
           class="uk-button uk-button-text">Sell</a>
    </div>
</div>