apps/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    # Default
    path("admin/", admin.site.urls),
    # Custom
    path("", RedirectView.as_view(pattern_name="account:login-view", permanent=False)),
    path("account/", include(("apps.account.urls", "apps.account"), namespace="account")),
    path("faction/", include(("apps.faction.urls", "apps.faction"), namespace="faction")),
    path("finance/", include(("apps.finance.urls", "apps.finance"), namespace="finance")),
    path("item/", include(("apps.item.urls", "apps.item"), namespace="item")),
    path("quest/", include(("apps.quest.urls", "apps.quest"), namespace="quest")),
    path("savegame/", include(("apps.savegame.urls", "apps.savegame"), namespace="savegame")),
    path(
        "skirmish/",
        include(("apps.skirmish.urls", "apps.skirmish"), namespace="skirmish"),
    ),
    path("training/", include(("apps.training.urls", "apps.training"), namespace="training")),
    path("warrior/", include(("apps.warrior.urls", "apps.month"), namespace="warrior")),
    path("month/", include(("apps.month.urls", "apps.month"), namespace="month")),
]

apps/faction/urls.py
from django.urls import path

from apps.faction import views

urlpatterns = [
    path("faction/<int:pk>/item/htmx", views.FactionItemListView.as_view(), name="faction-item-list-htmx"),
    path("faction/<int:pk>/warrior/htmx", views.FactionWarriorListView.as_view(), name="faction-warrior-list-htmx"),
    path(
        "faction/<int:pk>/captured-warrior/htmx",
        views.FactionCapturedWarriorListView.as_view(),
        name="faction-captured-warrior-list-htmx",
    ),
    path("faction/<int:pk>", views.FactionDetailView.as_view(), name="faction-detail-view"),
    path(
        "faction/<int:pk>/draft/fyrd",
        views.DraftWarriorFromFyrdView.as_view(),
        name="faction-draft-warrior-from-fyrd-view",
    ),
    path("faction/<int:pk>/costs/monthly", views.MonthlyCostOverview.as_view(), name="faction-monthly-costs-view"),
    path("faction/<int:pk>/town-square", views.TownSquareView.as_view(), name="town-square-view"),
    path("faction/<int:pk>/shop/item/htmx", views.FactionShopItemListView.as_view(), name="shop-item-list-htmx"),
]

apps/item/urls.py
from django.urls import path

from apps.item import views

urlpatterns = [
    path("<int:pk>/sell", views.ItemSellView.as_view(), name="item-sell-view"),
    path("<int:pk>/buy", views.ItemBuyView.as_view(), name="item-buy-view"),
]

apps/warrior/urls.py
from django.urls import path

from apps.warrior import views

urlpatterns = [
    path("warrior/<int:pk>", views.WarriorDetailView.as_view(), name="warrior-detail-view"),
    path(
        "warrior/<int:pk>/captured/recruit/faction/<int:faction_id>",
        views.WarriorRecruitCapturedView.as_view(),
        name="warrior-recruit-captured-view",
    ),
    path(
        "warrior/<int:pk>/captured/enslave/faction/<int:faction_id>",
        views.WarriorEnslaveCapturedView.as_view(),
        name="warrior-enslave-captured-view",
    ),
    path(
        "warrior/<int:pk>/partial-update/<str:htmx_attribute>",
        views.WarriorWeaponUpdateView.as_view(),
        name="warrior-partial-update-view",
    ),
]

apps/faction/models/culture.py
from django.db import models

from apps.faction.managers.culture import CultureManager


class Culture(models.Model):
    name = models.CharField("Name", max_length=100)
    locale = models.CharField("Locale", max_length=10)

    objects = CultureManager()

    class Meta:
        verbose_name = "Culture"
        verbose_name_plural = "Cultures"
        default_related_name = "cultures"

    def __str__(self) -> str:
        return self.name

apps/skirmish/models/warrior.py
from django.db import models

from apps.common.domain.dice import DiceNotation
from apps.faction.models.culture import Culture
from apps.item.models.item import Item
from apps.item.models.item_type import ItemType
from apps.skirmish.choices.skirmish_action import SkirmishActionChoices
from apps.skirmish.managers.warrior import WarriorManager
from apps.skirmish.services.skirmish.skirmish_action_decision import SkirmishActionDecisionService


# TODO: move to warrior app?
# TODO: permanent injuries would be nice -> each has a modificator and reduces a value like HP or dex
#  -> ankle -> reduce dex, missing finger -> strength etc.
class Warrior(models.Model):
    NO_WEAPON_ATTACK = "1d3"
    NO_ARMOR_DEFENSE = "1d3"

    class ConditionChoices(models.IntegerChoices):
        CONDITION_HEALTHY = 1, "Healthy"
        CONDITION_UNCONSCIOUS = 2, "Unconscious"
        CONDITION_FLEEING = 3, "Fleeing"
        CONDITION_DEAD = 4, "Dead"

    name = models.CharField("Name", max_length=100)
    culture = models.ForeignKey(Culture, verbose_name="Culture", on_delete=models.CASCADE)
    faction = models.ForeignKey(
        "faction.Faction", verbose_name="Faction", null=True, blank=True, on_delete=models.CASCADE
    )
    savegame = models.ForeignKey("savegame.Savegame", verbose_name="Savegame", on_delete=models.CASCADE)

    avatar_id = models.PositiveSmallIntegerField("Avatar-ID", default=1)

    strength = models.PositiveSmallIntegerField("Strength")
    strength_progress = models.PositiveSmallIntegerField("Strength progress", default=0)

    dexterity = models.PositiveSmallIntegerField("Dexterity")
    dexterity_progress = models.PositiveSmallIntegerField("Dexterity progress", default=0)

    current_health = models.SmallIntegerField("Current health")
    max_health = models.PositiveSmallIntegerField("Maximum health")
    health_progress = models.PositiveSmallIntegerField("Health progress", default=0)

    current_morale = models.SmallIntegerField("Current morale")
    max_morale = models.PositiveSmallIntegerField("Maximum morale")
    morale_progress = models.PositiveSmallIntegerField("Morale progress", default=0)

    experience = models.PositiveIntegerField("Experience", default=0)
    monthly_salary = models.PositiveSmallIntegerField("Monthly salary", default=0)

    recruitment_price = models.PositiveSmallIntegerField("Recruitment price", default=0)

    last_used_skirmish_action = models.PositiveSmallIntegerField(
        choices=SkirmishActionChoices.choices, blank=True, null=True
    )

    condition = models.PositiveSmallIntegerField(
        "Condition",
        choices=ConditionChoices.choices,
        default=ConditionChoices.CONDITION_HEALTHY,
    )

    weapon = models.OneToOneField(
        Item,
        verbose_name="Weapon",
        related_name="warrior_weapon",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    armor = models.OneToOneField(
        Item,
        verbose_name="Armor",
        related_name="warrior_armor",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )

    objects = WarriorManager()

    class Meta:
        verbose_name = "Warrior"
        verbose_name_plural = "Warriors"
        default_related_name = "warriors"

    def __str__(self) -> str:
        return self.name

    # TODO: add property when a certain value is really high to add a nickname like "Victor the Fast"
    #  (good and bad cases)

    @property
    def avatar_url(self) -> str:
        return f"img/warrior/avatars/avatar_{self.avatar_id}.jpg"

    @property
    def is_dead(self) -> bool:
        return self.condition == self.ConditionChoices.CONDITION_DEAD

    @property
    def is_unconscious(self) -> bool:
        return self.condition == self.ConditionChoices.CONDITION_UNCONSCIOUS

    @property
    def is_fleeing(self) -> bool:
        return self.condition == self.ConditionChoices.CONDITION_FLEEING

    @property
    def is_healthy(self) -> bool:
        return self.condition == self.ConditionChoices.CONDITION_HEALTHY

    @property
    def slavery_selling_price(self) -> int:
        return int(self.recruitment_price / 2)

    def get_skirmish_actions(self) -> list[tuple]:
        # TODO: show only the ones the warrior has depending on his level
        # TODO: use XP to add more skirmish actions -> every level gets a fixed action to keep it simple
        return SkirmishActionChoices.choices

    def decide_skirmish_action(self) -> [int, str]:
        service = SkirmishActionDecisionService(warrior=self)
        return service.process()

    def get_weapon_or_fallback(self) -> Item:
        return (
            self.weapon
            if self.weapon
            else Item(
                type=ItemType.objects.get(is_fallback=True, function=ItemType.FunctionChoices.FUNCTION_WEAPON),
                owner=self.faction,
            )
        )

    def get_armor_or_fallback(self) -> Item:
        return (
            self.armor
            if self.armor
            else Item(
                type=ItemType.objects.get(is_fallback=True, function=ItemType.FunctionChoices.FUNCTION_ARMOR),
                owner=self.faction,
            )
        )

    def roll_attack(self) -> int:
        item = self.get_weapon_or_fallback()
        return DiceNotation(dice_string=item.type.base_value, modifier=item.modifier).result

    def roll_defense(self) -> int:
        item = self.get_armor_or_fallback()
        return DiceNotation(dice_string=item.type.base_value, modifier=item.modifier).result

apps/faction/views.py
import json

from django.db.models import Sum
from django.shortcuts import render
from django.views import generic
from queuebie.runner import handle_message

from apps.faction.messages.commands.warrior import DraftWarriorFromFyrd
from apps.faction.models.faction import Faction
from apps.savegame.models.savegame import Savegame
from apps.skirmish.models.warrior import Warrior


class FactionDetailView(generic.DetailView):
    model = Faction
    template_name = "faction/faction_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["warrior_list"] = Warrior.objects.exclude_dead().filter_faction(faction_id=self.object.id)
        return context


class FactionItemListView(generic.DetailView):
    model = Faction
    template_name = "faction/item/components/item_list.html"


class FactionWarriorListView(generic.DetailView):
    model = Faction
    template_name = "faction/warrior/components/warrior_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["warrior_list"] = Warrior.objects.exclude_dead().filter_faction(faction_id=self.object.id)
        return context


class FactionCapturedWarriorListView(generic.DetailView):
    model = Faction
    template_name = "faction/warrior/components/captured_warrior_list.html"


class DraftWarriorFromFyrdView(generic.DetailView):
    model = Faction
    http_method_names = ("post",)
    template_name = "faction/warrior/components/fyrd_card.html"

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        current_savegame: Savegame = Savegame.objects.get_current_savegame(user_id=self.request.user.id)

        handle_message(DraftWarriorFromFyrd(faction=obj, month=current_savegame.current_month))
        response = render(request, self.template_name, {"faction": obj})

        response["HX-Trigger"] = json.dumps(
            {
                "notification": "New Warrior drafted",
                "loadFactionWarriorList": "-",
                "loadFactionItemList": "-",
            }
        )

        return response


class MonthlyCostOverview(generic.DetailView):
    model = Faction
    template_name = "faction/faction/components/current_cost_card.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Fetch current savegame record
        current_savegame: Savegame = Savegame.objects.get_current_savegame(user_id=self.request.user.id)

        player_faction = current_savegame.player_faction
        # TODO: put in manager
        context["monthly_salary_amount"] = (
            player_faction.warriors.exclude(condition=Warrior.ConditionChoices.CONDITION_DEAD).aggregate(
                sum_monthly_salary=Sum("monthly_salary")
            )["sum_monthly_salary"]
            or 0
        )
        return context


class TownSquareView(generic.DetailView):
    model = Faction
    template_name = "faction/town_square.html"

    def get_queryset(self):
        current_savegame: Savegame = Savegame.objects.get_current_savegame(user_id=self.request.user.id)
        return super().get_queryset().for_savegame(savegame_id=current_savegame)


class FactionShopItemListView(generic.DetailView):
    model = Faction
    template_name = "faction/item/components/shop_item_list.html"

    def get_queryset(self):
        current_savegame: Savegame = Savegame.objects.get_current_savegame(user_id=self.request.user.id)
        return super().get_queryset().for_savegame(savegame_id=current_savegame)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["item_list"] = self.object.available_items.all()
        return context

apps/warrior/views.py
import json
from http import HTTPStatus

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views import generic
from queuebie.runner import handle_message

from apps.faction.models.faction import Faction
from apps.savegame.models.savegame import Savegame
from apps.skirmish.models.warrior import Warrior
from apps.warrior.forms.warrior import WarriorForm
from apps.warrior.messages.commands.warrior import EnslaveCapturedWarrior, RecruitCapturedWarrior


class WarriorDetailView(generic.DetailView):
    model = Warrior
    template_name = "warrior/warrior_detail.html"


class WarriorWeaponUpdateView(generic.UpdateView):
    model = Warrior
    form_class = WarriorForm
    template_name = "warrior/components/warrior_field_edit.html"
    object = None
    htmx_field = None

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        self.htmx_field = self.kwargs.get("htmx_attribute", None)
        kwargs["htmx_field"] = self.htmx_field
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        return render(self.request, "warrior/components/warrior_field_display.html", self.get_context_data())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object"] = self.object
        context["attribute"] = self.htmx_field
        context["field_value"] = getattr(self.object, self.htmx_field)
        return context


class WarriorRecruitCapturedView(generic.DetailView):
    model = Warrior
    http_method_names = ("post",)

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        faction = get_object_or_404(Faction, pk=kwargs["faction_id"])
        current_savegame: Savegame = Savegame.objects.get_current_savegame(user_id=self.request.user.id)

        handle_message(RecruitCapturedWarrior(faction=faction, warrior=obj, month=current_savegame.current_month))

        response = HttpResponse(status=HTTPStatus.OK)
        response["HX-Trigger"] = json.dumps(
            {
                "notification": "Captured warrior joined your ranks",
                "loadFactionWarriorList": "-",
                "loadFactionCapturedWarriorList": "-",
            }
        )

        return response


class WarriorEnslaveCapturedView(generic.DetailView):
    model = Warrior
    http_method_names = ("post",)

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        faction = get_object_or_404(Faction, pk=kwargs["faction_id"])
        current_savegame: Savegame = Savegame.objects.get_current_savegame(user_id=self.request.user.id)

        handle_message(EnslaveCapturedWarrior(faction=faction, warrior=obj, month=current_savegame.current_month))

        response = HttpResponse(status=HTTPStatus.OK)
        response["HX-Trigger"] = json.dumps(
            {
                "notification": "Captured warrior was sold into slavery",
                "loadFactionCapturedWarriorList": "-",
            }
        )

        return response

apps/faction/templates/faction/warrior/components/captured_warrior_list.html
<div hx-get="{% url 'faction:faction-captured-warrior-list-htmx' faction.id %}"
     hx-trigger="loadFactionCapturedWarriorList from:body">
    <h2>Captured warriors</h2>
    {# todo: captured warriors never heal HP #}
    {% for warrior in faction.captured_warriors.all %}
        {% include 'warrior/components/warrior_card.html' with warrior=warrior faction=faction is_captured=True %}
    {% endfor %}
</div>

apps/faction/templates/faction/warrior/components/fyrd_card.html
<div id="fyrd-card" class="uk-card uk-card-default uk-card-body uk-margin-bottom">
    <h3>Fyrd</h3>
    <table class="uk-table">
        <tbody>
        <tr>
            <td>Reserve</td>
            <td>{{ faction.fyrd_reserve }}</td>
        </tr>
        </tbody>
    </table>
    {% if faction.fyrd_reserve %}
        <button hx-post="{% url 'faction:faction-draft-warrior-from-fyrd-view' faction.id %}"
                hx-target="#fyrd-card"
                hx-swap="outerHTML"
                class="uk-button uk-button-primary">Draft warrior
        </button>
    {% endif %}
</div>

apps/faction/templates/faction/warrior/components/pub_warrior_card.html
{% load obsucrify static %}
<div class="uk-card uk-card-default uk-margin-bottom">
    <div class="uk-card-header">
        <div class="uk-grid-small uk-flex-middle" uk-grid>
            <div class="uk-width-auto">
                {% include 'common/components/svg_icon.html' with icon_name='swordman' size='xl' %}
            </div>
            <div class="uk-width-expand">
                <h3 class="uk-card-title uk-margin-remove-bottom">{{ warrior.name }}</h3>
                <p class="uk-text-meta uk-margin-remove-top">
                    <i class="fa-solid fa-layer-group"></i> <i>{{ warrior.experience }} XP</i>&nbsp;
                    <i class="fa-solid fa-coins"></i> <i>{{ warrior.monthly_salary }}</i>&nbsp;
                    <i class="fa-solid fa-heart"></i>
                    <i>{{ warrior.max_health|obscurify:20 }}</i>&nbsp;
                    <i class="fa-solid fa-bolt"></i> <i>{{ warrior.max_morale|obscurify:10 }}</i>&nbsp;
                    <i class="fa-solid fa-user-injured"></i> <i>{{ warrior.get_condition_display }}</i>
                </p>
            </div>
        </div>
    </div>
    <div class="uk-card-body uk-text-left">
        <div class="uk-grid uk-child-width-expand@s" uk-grid>
            <div>
                <table class="uk-table">
                    <tr>
                        <td>Culture</td>
                        <td>{{ warrior.culture.name }}</td>
                    </tr>
                    <tr>
                        <td>Strength</td>
                        <td>{{ warrior.strength|obscurify:10 }}</td>
                    </tr>
                    <tr>
                        <td>Dexterity</td>
                        <td>{{ warrior.dexterity|obscurify:10 }}</td>
                    </tr>
                </table>
            </div>
            <div>
                <table class="uk-table">

                    <tr>
                        <td>Weapon</td>
                        <td>{% if warrior.weapon %}{{ warrior.weapon.display_name }}{% else %}-{% endif %}</td>
                    </tr>
                    <tr>
                        <td>Armor</td>
                        <td>{% if armor.weapon %}{{ warrior.armor.display_name }}{% else %}-{% endif %}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="uk-card-footer">
        {# TODO: implement recruiting #}
        <a href="#" class="uk-button uk-button-text">Recruit for {{ warrior.recruitment_price }} silver</a>
    </div>
</div>

apps/faction/templates/faction/warrior/components/warrior_list.html
<div hx-get="{% url 'faction:faction-warrior-list-htmx' faction.id %}"
     hx-trigger="loadFactionWarriorList from:body">
    <h2>Warriors</h2>
    {% for warrior in warrior_list %}
        {% include 'warrior/components/warrior_card.html' with warrior=warrior %}
    {% endfor %}
</div>