apps/account/urls.py
from django.contrib.auth.decorators import login_not_required
from django.urls import path

from apps.account import views

urlpatterns = [
    path("login/", login_not_required(views.LoginView.as_view()), name="login-view"),
    path("logout/", views.LogoutView.as_view(), {}, name="logout-view"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard-view"),
]

apps/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    # Default
    path("admin/", admin.site.urls),
    # Custom
    path("", RedirectView.as_view(pattern_name="account:login-view", permanent=False)),
    path("account/", include(("apps.account.urls", "apps.account"), namespace="account")),
    path("faction/", include(("apps.faction.urls", "apps.faction"), namespace="faction")),
    path("finance/", include(("apps.finance.urls", "apps.finance"), namespace="finance")),
    path("item/", include(("apps.item.urls", "apps.item"), namespace="item")),
    path("quest/", include(("apps.quest.urls", "apps.quest"), namespace="quest")),
    path("savegame/", include(("apps.savegame.urls", "apps.savegame"), namespace="savegame")),
    path(
        "skirmish/",
        include(("apps.skirmish.urls", "apps.skirmish"), namespace="skirmish"),
    ),
    path("training/", include(("apps.training.urls", "apps.training"), namespace="training")),
    path("warrior/", include(("apps.warrior.urls", "apps.month"), namespace="warrior")),
    path("month/", include(("apps.month.urls", "apps.month"), namespace="month")),
]

apps/faction/urls.py
from django.urls import path

from apps.faction import views

urlpatterns = [
    path("faction/<int:pk>/item/htmx", views.FactionItemListView.as_view(), name="faction-item-list-htmx"),
    path("faction/<int:pk>/warrior/htmx", views.FactionWarriorListView.as_view(), name="faction-warrior-list-htmx"),
    path(
        "faction/<int:pk>/captured-warrior/htmx",
        views.FactionCapturedWarriorListView.as_view(),
        name="faction-captured-warrior-list-htmx",
    ),
    path("faction/<int:pk>", views.FactionDetailView.as_view(), name="faction-detail-view"),
    path(
        "faction/<int:pk>/draft/fyrd",
        views.DraftWarriorFromFyrdView.as_view(),
        name="faction-draft-warrior-from-fyrd-view",
    ),
    path("faction/<int:pk>/costs/monthly", views.MonthlyCostOverview.as_view(), name="faction-monthly-costs-view"),
    path("faction/<int:pk>/town-square", views.TownSquareView.as_view(), name="town-square-view"),
    path("faction/<int:pk>/shop/item/htmx", views.FactionShopItemListView.as_view(), name="shop-item-list-htmx"),
]

apps/finance/urls.py
from django.urls import path

from apps.finance import views

urlpatterns = [
    path("<int:faction_id>", views.TransactionListView.as_view(), name="transaction-list-view"),
]

apps/item/urls.py
from django.urls import path

from apps.item import views

urlpatterns = [
    path("<int:pk>/sell", views.ItemSellView.as_view(), name="item-sell-view"),
    path("<int:pk>/buy", views.ItemBuyView.as_view(), name="item-buy-view"),
]

apps/month/urls.py
from django.urls import path

from apps.month import views

urlpatterns = [
    path("finish/", views.FinishMonthView.as_view(), name="finish-month-view"),
    path("player-month-log/", views.PlayerMonthLogListView.as_view(), name="player-month-log-list-view"),
    path(
        "player-month-log/<int:pk>/remove/",
        views.AcknowledgePlayerMonthLogView.as_view(),
        name="player-month-log-remove-view",
    ),
]

apps/common/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tettenhall - The Game</title>
    <link rel="stylesheet" href="{% static '@fortawesome/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'uikit/dist/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'css/colors.css' %}">
    <link rel="stylesheet" href="{% static 'css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/progress-bar.css' %}">
</head>
<body>
<nav class="uk-navbar-container uk-margin" uk-navbar>
    <div class="uk-navbar-left">
        <a class="uk-navbar-item uk-logo uk-margin-left" href="{% url 'account:dashboard-view' %}">Tettenhall</a>

        {% if request.user.is_authenticated and current_savegame %}
            <ul class="uk-navbar-nav">
                <li>
                    <a href="{% url 'faction:faction-detail-view' current_savegame.player_faction_id %}">
                        {{ current_savegame.player_faction }}
                    </a>
                </li>
                <li>
                    <a href="{% url 'faction:town-square-view' current_savegame.player_faction_id %}">
                        {{ current_savegame.player_faction.town_name }}
                    </a>
                </li>
                <li>
                    <a href="{% url 'training:training-list-view' %}">
                        Training
                    </a>
                </li>
                <li>
                    <a href="{% url 'skirmish:skirmish-list-view' %}">
                        Skirmishes
                    </a>
                </li>
                <li>
                    <a href="{% url 'finance:transaction-list-view' current_savegame.player_faction_id %}">
                        Finance
                    </a>
                </li>
                <li>
                    <a href="#">
                        Estates {# todo: implement me #}
                    </a>
                </li>
            </ul>
            <div class="uk-navbar-item">
                <span >{% include 'common/components/svg_icon.html' with icon_name="warrior_face" size='sm' %} {{ faction_warriors.count }}</span>
                <span >{% include 'common/components/svg_icon.html' with icon_name="silver" size='sm' %} {{ current_balance }}</span>
                <span >{% include 'common/components/svg_icon.html' with icon_name="crossed_swords" size='sm' %} {{ open_skirmishes.count }}</span>
            </div>
        {% endif %}
    </div>
    <div class="uk-navbar-right uk-margin-right">
        <ul class="uk-navbar-nav">
            {% if request.user.is_authenticated and current_savegame %}
                <li class="uk-active">
                    <a hx-post="{% url 'month:finish-month-view' %}">
                        Finish month
                    </a>
                </li>
            {% endif %}
            {% if request.user.is_authenticated %}
                <li>
                    <a href="#">{{ current_savegame.player_faction|default:"No savegame" }} / {{ request.user }}</a>
                    <div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            <li><a href="{% url "savegame:savegame-list-view" %}">Savegames</a></li>
                            <li><a href="{% url "account:logout-view" %}">Logout</a></li>
                        </ul>
                    </div>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="uk-container-expand uk-margin-left uk-margin-right">
    {% block content %}{% endblock %}
</div>

<div id="hidden-box" class="uk-hidden"></div>

<script src="{% static 'htmx.org/dist/htmx.js' %}"></script>
<script src="{% static 'uikit/dist/js/uikit.js' %}"></script>
<script src="{% static 'js/idiomorph-ext.min.js' %}"></script>
<script type="text/javascript">
    // Add CSRF token to HTMX plugin for being able to make AJAX calls
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    });
    // Notifications
    document.body.addEventListener("notification", function (e) {
        UIkit.notification({
            message: e.detail.value,
            status: 'success',
            pos: 'top-center',
            timeout: 1000,
        });
    });
    document.body.addEventListener('htmx:beforeOnLoad', function (evt) {
        if (500 <= evt.detail.xhr.status && evt.detail.xhr.status < 600) {
            UIkit.notification({
                message: "An error has occured.",
                status: 'danger',
                pos: 'bottom-center',
                timeout: 1000,
            });
        }
    });

    {% for message in messages %}
        UIkit.notification({
            message: "{{ message|safe }}",
            status: "{{ message.level_tag }}",
            pos: 'top-center',
            timeout: 1000,
        });
    {% endfor %}
</script>
</body>
</html>